name: tilseg_mac_2024
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.8.1
  - appnope=0.1.4
  - asttokens=2.4.1
  - blas=1.0
  - blosc=1.21.5
  - bottleneck=1.3.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.27.0
  - c-blosc2=2.13.2
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - charls=2.4.2
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - icu=73.2
  - imagecodecs=2024.1.1
  - imageio=2.34.0
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.3
  - ipython=8.22.1
  - jasper=4.2.1
  - jedi=0.19.1
  - joblib=1.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jxrlib=1.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.2
  - libass=0.17.1
  - libavif16=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libdicom=1.0.5
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libhwloc=2.9.3
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.21
  - libopencv=4.9.0
  - libopenvino=2023.3.0
  - libopenvino-auto-batch-plugin=2023.3.0
  - libopenvino-auto-plugin=2023.3.0
  - libopenvino-hetero-plugin=2023.3.0
  - libopenvino-ir-frontend=2023.3.0
  - libopenvino-onnx-frontend=2023.3.0
  - libopenvino-paddle-frontend=2023.3.0
  - libopenvino-pytorch-frontend=2023.3.0
  - libopenvino-tensorflow-frontend=2023.3.0
  - libopenvino-tensorflow-lite-frontend=2023.3.0
  - libopus=1.3.1
  - libpng=1.6.43
  - libprotobuf=4.25.2
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.5
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.9.0
  - openh264=2.4.1
  - openjpeg=2.5.1
  - openslide=4.0.0
  - openslide-python=1.3.1
  - openssl=3.2.1
  - p11-kit=0.24.1
  - packaging=23.2
  - pandas=2.1.4
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.2
  - py-opencv=4.9.0
  - pygments=2.17.2
  - pyparsing=3.1.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyzmq=25.1.2
  - rav1e=0.6.6
  - readline=8.2
  - scikit-image=0.22.0
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - setuptools=69.1.1
  - six=1.16.0
  - snappy=1.1.10
  - stack_data=0.6.2
  - svt-av1=1.8.0
  - tbb=2021.11.0
  - threadpoolctl=2.2.0
  - tifffile=2024.2.12
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.1
  - typing_extensions=4.10.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.42.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
prefix: /Users/lisacarr/opt/anaconda3/envs/tilseg_mac2
